# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               AMPed
tagline:             'a Web Dev Adventure blog by amarkpark'
description:         '<a href="http://amarkpark.com"><img src="./public/sAMPsmed.png" width="166" height="132" border="0"></a>'
url:                 http://ampblog.amarkpark.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              amarkpark
  url:               https://twitter.com/amarkpark
  email:             amarkpark@gmail.com

# Custom vars
version:             1.0.0

